/*
 * This file is auto-generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Command: python select_generator.py .
 */

/*
 * This file is part of LibCSS
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2017 The NetSurf Project
 */

#ifndef CSS_COMPUTED_COMPUTED_H_
#define CSS_COMPUTED_COMPUTED_H_

#include "select/calc.h"

typedef union {
	css_fixed value;
	lwc_string *calc;
} css_fixed_or_calc;


struct css_computed_style_i {
/*
 * Property                       Size (bits)     Size (bytes)
 * ---                            ---             ---
 * align_content                    3             
 * align_items                      3             
 * align_self                       3             
 * background_attachment            2             
 * background_color                 2               4
 * background_image                 1             sizeof(ptr)
 * background_position              1 + 12          8
 * background_repeat                3             
 * border_bottom_color              2               4
 * border_bottom_style              4             
 * border_bottom_width              3 + 6           4
 * border_collapse                  2             
 * border_left_color                2               4
 * border_left_style                4             
 * border_left_width                3 + 6           4
 * border_right_color               2               4
 * border_right_style               4             
 * border_right_width               3 + 6           4
 * border_spacing                   1 + 12          8
 * border_top_color                 2               4
 * border_top_style                 4             
 * border_top_width                 3 + 6           4
 * bottom                           2 + 6           4
 * box_sizing                       2             
 * break_after                      4             
 * break_before                     4             
 * break_inside                     4             
 * caption_side                     2             
 * clear                            3             
 * clip                             6 + 24         16
 * color                            1               4
 * column_count                     2               4
 * column_fill                      2             
 * column_gap                       2 + 6           4
 * column_rule_color                2               4
 * column_rule_style                4             
 * column_rule_width                3 + 6           4
 * column_span                      2             
 * column_width                     2 + 6           4
 * direction                        2             
 * display                          5             
 * empty_cells                      2             
 * fill_opacity                     1               4
 * flex_basis                       2 + 6           4
 * flex_direction                   3             
 * flex_grow                        1               4
 * flex_shrink                      1               4
 * flex_wrap                        2             
 * float                            2             
 * font_size                        4 + 6           4
 * font_style                       2             
 * font_variant                     2             
 * font_weight                      4             
 * grid_auto_flow                   3             
 * grid_column_end                  2               4
 * grid_column_start                2               4
 * grid_row_end                     2               4
 * grid_row_start                   2               4
 * height                           2 + 6           4
 * justify_content                  3             
 * left                             2 + 6           4
 * letter_spacing                   2 + 6           4
 * line_height                      2 + 6           4
 * list_style_image                 1             sizeof(ptr)
 * list_style_position              2             
 * list_style_type                  6             
 * margin_bottom                    2 + 6           4
 * margin_left                      2 + 6           4
 * margin_right                     2 + 6           4
 * margin_top                       2 + 6           4
 * max_height                       2 + 6           4
 * max_width                        2 + 6           4
 * min_height                       2 + 6           4
 * min_width                        2 + 6           4
 * opacity                          1               4
 * order                            1               4
 * orphans                          1               4
 * outline_color                    2               4
 * outline_style                    4             
 * outline_width                    3 + 6           4
 * overflow_x                       3             
 * overflow_y                       3             
 * padding_bottom                   1 + 6           4
 * padding_left                     1 + 6           4
 * padding_right                    1 + 6           4
 * padding_top                      1 + 6           4
 * page_break_after                 3             
 * page_break_before                3             
 * page_break_inside                2             
 * position                         3             
 * right                            2 + 6           4
 * row_gap                          2 + 6           4
 * stroke_opacity                   1               4
 * table_layout                     2             
 * text_align                       4             
 * text_decoration                  5             
 * text_indent                      1 + 6           4
 * text_transform                   3             
 * top                              2 + 6           4
 * unicode_bidi                     2             
 * vertical_align                   4 + 6           4
 * visibility                       2             
 * white_space                      3             
 * widows                           1               4
 * width                            2 + 6           4
 * word_spacing                     2 + 6           4
 * writing_mode                     2             
 * z_index                          2               4
 * 
 * Encode content as an array of content items, terminated with a blank entry.
 * 
 * content                          2             sizeof(ptr)
 * 
 * Encode counter_increment as an array of name, value pairs, terminated with a
 * blank entry.
 * 
 * counter_increment                1             sizeof(ptr)
 * 
 * Encode counter_reset as an array of name, value pairs, terminated with a
 * blank entry.
 * 
 * counter_reset                    1             sizeof(ptr)
 * 
 * Encode cursor uri(s) as an array of string objects, terminated with a blank
 * entry
 * 
 * cursor                           5             sizeof(ptr)
 * 
 * Encode font family as an array of string objects, terminated with a blank
 * entry.
 * 
 * font_family                      3             sizeof(ptr)
 * 
 * Encode grid tracks as an array of track items, terminated with a zero-value
 * entry.
 * 
 * grid_template_columns            2             sizeof(ptr)
 * 
 * Encode grid tracks as an array of track items, terminated with a zero-value
 * entry.
 * 
 * grid_template_rows               2             sizeof(ptr)
 * 
 * Encode quotes as an array of string objects, terminated with a blank entry.
 * 
 * quotes                           1             sizeof(ptr)
 * 
 * ---                            ---             ---
 *                                528 bits        256 + 10sizeof(ptr) bytes
 *                                ===================
 *                                322 + 10sizeof(ptr) bytes
 * 
 * Bit allocations:
 * 
 * 0  wwwwwwwwttttttttrrrrrrrriiiiiiii
 * width; top; row_gap; right
 * 
 * 1  mmmmmmmmiiiiiiiiaaaaaaaaxxxxxxxx
 * min_width; min_height; max_width; max_height
 * 
 * 2  mmmmmmmmaaaaaaaarrrrrrrrgggggggg
 * margin_top; margin_right; margin_left; margin_bottom
 * 
 * 3  lllllllleeeeeeeeffffffffhhhhhhhh
 * line_height; letter_spacing; left; height
 * 
 * 4  ffffffffccccccccoooooooobbbbbbbb
 * flex_basis; column_width; column_gap; bottom
 * 
 * 5  bbbbbbbbbbbbbaaaaaaaaaaaaallllll
 * border_spacing; background_position; list_style_type
 * 
 * 6  cccccccccbbbbbbbbbooooooooottttt
 * column_rule_width; border_top_width; border_right_width; text_decoration
 * 
 * 7  tttttttpppppppaaaaaaadddddddeeee
 * text_indent; padding_top; padding_right; padding_left; text_align
 * 
 * 8  pppppppcccccooooffffllllbbbbrrrr
 * padding_bottom; cursor; outline_style; font_weight; column_rule_style;
 * break_inside; break_before
 * 
 * 9  vvvvvvvvvvffffffffffooooooooowww
 * vertical_align; font_size; outline_width; white_space
 * 
 * 10 bbbboooorrrrddddeeeetttpppaaaggg
 * break_after; border_top_style; border_right_style; border_left_style;
 * border_bottom_style; text_transform; position; page_break_before;
 * page_break_after
 * 
 * 11 cccccccccccccccccccccccccccccczz
 * clip; z_index
 * 
 * 12 ooovvvjjjgggffflllcccbbbaaaiiiww
 * overflow_y; overflow_x; justify_content; grid_auto_flow; font_family;
 * flex_direction; clear; background_repeat; align_self; align_items;
 * writing_mode
 * 
 * 13 fflleeddccoouummnnaabbrriittppBB
 * float; flex_wrap; empty_cells; direction; content; column_span;
 * column_rule_color; column_fill; column_count; caption_side; box_sizing;
 * border_top_color; border_right_color; border_left_color; border_collapse;
 * border_bottom_color
 * 
 * 14 bbbbbbbbbooooooooowwwwwwwwdddddi
 * border_left_width; border_bottom_width; word_spacing; display; widows
 * 
 * 15 aaavvuuttppoollggrriiddccmmffnns
 * align_content; visibility; unicode_bidi; table_layout; page_break_inside;
 * outline_color; list_style_position; grid_template_rows;
 * grid_template_columns; grid_row_start; grid_row_end; grid_column_start;
 * grid_column_end; font_variant; font_style; stroke_opacity
 * 
 * 16 bbaaqorplfeicuCk................
 * background_color; background_attachment; quotes; orphans; order; opacity;
 * list_style_image; flex_shrink; flex_grow; fill_opacity; counter_reset;
 * counter_increment; color; background_image
 */
	uint32_t bits[17];
	
	css_color background_color;
	lwc_string *background_image;
	css_fixed background_position_a;
	css_fixed background_position_b;
	css_color border_bottom_color;
	css_fixed border_bottom_width;
	css_color border_left_color;
	css_fixed border_left_width;
	css_color border_right_color;
	css_fixed border_right_width;
	css_fixed border_spacing_a;
	css_fixed border_spacing_b;
	css_color border_top_color;
	css_fixed border_top_width;
	css_fixed bottom;
	css_fixed clip_a;
	css_fixed clip_b;
	css_fixed clip_c;
	css_fixed clip_d;
	css_color color;
	int32_t column_count;
	css_fixed column_gap;
	css_color column_rule_color;
	css_fixed column_rule_width;
	css_fixed column_width;
	css_fixed fill_opacity;
	css_fixed flex_basis;
	css_fixed flex_grow;
	css_fixed flex_shrink;
	css_fixed font_size;
	int32_t grid_column_end;
	int32_t grid_column_start;
	int32_t grid_row_end;
	int32_t grid_row_start;
	css_fixed height;
	css_fixed left;
	css_fixed letter_spacing;
	css_fixed line_height;
	lwc_string *list_style_image;
	css_fixed margin_bottom;
	css_fixed margin_left;
	css_fixed margin_right;
	css_fixed margin_top;
	css_fixed max_height;
	css_fixed max_width;
	css_fixed min_height;
	css_fixed min_width;
	css_fixed opacity;
	int32_t order;
	int32_t orphans;
	css_color outline_color;
	css_fixed outline_width;
	css_fixed padding_bottom;
	css_fixed padding_left;
	css_fixed padding_right;
	css_fixed padding_top;
	css_fixed right;
	css_fixed row_gap;
	css_fixed stroke_opacity;
	css_fixed text_indent;
	css_fixed top;
	css_fixed vertical_align;
	int32_t widows;
	css_fixed_or_calc width;
	css_fixed word_spacing;
	int32_t z_index;
};

struct css_computed_style {
	struct css_computed_style_i i;
	
	css_computed_content_item *content;
	css_computed_counter *counter_increment;
	css_computed_counter *counter_reset;
	lwc_string **cursor;
	lwc_string **font_family;
	css_computed_grid_track *grid_template_columns;
	css_computed_grid_track *grid_template_rows;
	lwc_string **quotes;
	
	struct css_computed_style *next;
	uint32_t count;
	uint32_t bin;
	css_calculator *calc;
};

#endif
