add_custom_command(
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/content/handlers/javascript/duktape/polyfill.js.inc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/content/handlers/javascript/duktape
    COMMAND ${PYTHON3} ${CMAKE_SOURCE_DIR}/utils/cmake_helper.py file-to-hex
        ${CMAKE_SOURCE_DIR}/src/content/handlers/javascript/duktape/polyfill.js
        ${CMAKE_CURRENT_BINARY_DIR}/content/handlers/javascript/duktape/polyfill.js.inc
        polyfill_js
    DEPENDS ${CMAKE_SOURCE_DIR}/src/content/handlers/javascript/duktape/polyfill.js
)
add_custom_command(
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/content/handlers/javascript/duktape/generics.js.inc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/content/handlers/javascript/duktape
    COMMAND ${PYTHON3} ${CMAKE_SOURCE_DIR}/utils/cmake_helper.py file-to-hex
        ${CMAKE_SOURCE_DIR}/src/content/handlers/javascript/duktape/generics.js
        ${CMAKE_CURRENT_BINARY_DIR}/content/handlers/javascript/duktape/generics.js.inc
        generics_js
    DEPENDS ${CMAKE_SOURCE_DIR}/src/content/handlers/javascript/duktape/generics.js
)
add_custom_target(duktape_js_inc DEPENDS
    ${CMAKE_CURRENT_BINARY_DIR}/content/handlers/javascript/duktape/polyfill.js.inc
    ${CMAKE_CURRENT_BINARY_DIR}/content/handlers/javascript/duktape/generics.js.inc
)

include_directories(${CMAKE_CURRENT_BINARY_DIR}/content/handlers/javascript/duktape)
file(GLOB DUKTAPE_BND ${CMAKE_SOURCE_DIR}/src/content/handlers/javascript/duktape/*.bnd)
file(GLOB WEBIDL_SOURCES ${CMAKE_SOURCE_DIR}/src/content/handlers/javascript/WebIDL/*.idl)
set(DUKTAPE_GEN_SOURCES
    ${CMAKE_BINARY_DIR}/duktape/application_cache.c
    ${CMAKE_BINARY_DIR}/duktape/attr.c
    ${CMAKE_BINARY_DIR}/duktape/audio_track.c
    ${CMAKE_BINARY_DIR}/duktape/audio_track_list.c
    ${CMAKE_BINARY_DIR}/duktape/autocomplete_error_event.c
    ${CMAKE_BINARY_DIR}/duktape/autocomplete_error_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/bar_prop.c
    ${CMAKE_BINARY_DIR}/duktape/before_unload_event.c
    ${CMAKE_BINARY_DIR}/duktape/broadcast_channel.c
    ${CMAKE_BINARY_DIR}/duktape/canvas_gradient.c
    ${CMAKE_BINARY_DIR}/duktape/canvas_pattern.c
    ${CMAKE_BINARY_DIR}/duktape/canvas_proxy.c
    ${CMAKE_BINARY_DIR}/duktape/canvas_rendering_context2d.c
    ${CMAKE_BINARY_DIR}/duktape/canvas_rendering_context2d_settings.c
    ${CMAKE_BINARY_DIR}/duktape/character_data.c
    ${CMAKE_BINARY_DIR}/duktape/close_event.c
    ${CMAKE_BINARY_DIR}/duktape/close_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/comment.c
    ${CMAKE_BINARY_DIR}/duktape/composition_event.c
    ${CMAKE_BINARY_DIR}/duktape/composition_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/console.c
    ${CMAKE_BINARY_DIR}/duktape/css.c
    ${CMAKE_BINARY_DIR}/duktape/css_grouping_rule.c
    ${CMAKE_BINARY_DIR}/duktape/css_import_rule.c
    ${CMAKE_BINARY_DIR}/duktape/css_margin_rule.c
    ${CMAKE_BINARY_DIR}/duktape/css_media_rule.c
    ${CMAKE_BINARY_DIR}/duktape/css_namespace_rule.c
    ${CMAKE_BINARY_DIR}/duktape/css_page_rule.c
    ${CMAKE_BINARY_DIR}/duktape/css_rule.c
    ${CMAKE_BINARY_DIR}/duktape/css_rule_list.c
    ${CMAKE_BINARY_DIR}/duktape/css_style_declaration.c
    ${CMAKE_BINARY_DIR}/duktape/css_style_rule.c
    ${CMAKE_BINARY_DIR}/duktape/css_style_sheet.c
    ${CMAKE_BINARY_DIR}/duktape/custom_event.c
    ${CMAKE_BINARY_DIR}/duktape/custom_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/data_transfer.c
    ${CMAKE_BINARY_DIR}/duktape/data_transfer_item.c
    ${CMAKE_BINARY_DIR}/duktape/data_transfer_item_list.c
    ${CMAKE_BINARY_DIR}/duktape/dedicated_worker_global_scope.c
    ${CMAKE_BINARY_DIR}/duktape/document.c
    ${CMAKE_BINARY_DIR}/duktape/document_fragment.c
    ${CMAKE_BINARY_DIR}/duktape/document_type.c
    ${CMAKE_BINARY_DIR}/duktape/dom_element_map.c
    ${CMAKE_BINARY_DIR}/duktape/dom_implementation.c
    ${CMAKE_BINARY_DIR}/duktape/dom_parser.c
    ${CMAKE_BINARY_DIR}/duktape/dom_settable_token_list.c
    ${CMAKE_BINARY_DIR}/duktape/dom_string_map.c
    ${CMAKE_BINARY_DIR}/duktape/dom_token_list.c
    ${CMAKE_BINARY_DIR}/duktape/drag_event.c
    ${CMAKE_BINARY_DIR}/duktape/drag_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/drawing_style.c
    ${CMAKE_BINARY_DIR}/duktape/element.c
    ${CMAKE_BINARY_DIR}/duktape/error_event.c
    ${CMAKE_BINARY_DIR}/duktape/error_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/event.c
    ${CMAKE_BINARY_DIR}/duktape/event_init.c
    ${CMAKE_BINARY_DIR}/duktape/event_listener.c
    ${CMAKE_BINARY_DIR}/duktape/event_modifier_init.c
    ${CMAKE_BINARY_DIR}/duktape/event_source.c
    ${CMAKE_BINARY_DIR}/duktape/event_source_init.c
    ${CMAKE_BINARY_DIR}/duktape/event_target.c
    ${CMAKE_BINARY_DIR}/duktape/external.c
    ${CMAKE_BINARY_DIR}/duktape/focus_event.c
    ${CMAKE_BINARY_DIR}/duktape/focus_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/hash_change_event.c
    ${CMAKE_BINARY_DIR}/duktape/hash_change_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/history.c
    ${CMAKE_BINARY_DIR}/duktape/hit_region_options.c
    ${CMAKE_BINARY_DIR}/duktape/html_all_collection.c
    ${CMAKE_BINARY_DIR}/duktape/html_anchor_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_applet_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_area_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_audio_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_base_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_body_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_br_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_button_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_canvas_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_collection.c
    ${CMAKE_BINARY_DIR}/duktape/html_data_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_data_list_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_details_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_dialog_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_directory_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_div_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_dlist_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_embed_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_field_set_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_font_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_form_controls_collection.c
    ${CMAKE_BINARY_DIR}/duktape/html_form_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_frame_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_frame_set_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_head_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_heading_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_hr_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_html_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_iframe_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_image_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_input_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_keygen_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_label_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_legend_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_li_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_link_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_map_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_marquee_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_media_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_menu_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_menu_item_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_meta_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_meter_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_mod_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_object_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_olist_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_opt_group_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_option_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_options_collection.c
    ${CMAKE_BINARY_DIR}/duktape/html_output_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_paragraph_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_param_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_picture_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_pre_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_progress_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_quote_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_script_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_select_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_source_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_span_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_style_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_table_caption_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_table_cell_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_table_col_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_table_data_cell_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_table_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_table_header_cell_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_table_row_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_table_section_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_template_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_text_area_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_time_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_title_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_track_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_ulist_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_unknown_element.c
    ${CMAKE_BINARY_DIR}/duktape/html_video_element.c
    ${CMAKE_BINARY_DIR}/duktape/image_bitmap.c
    ${CMAKE_BINARY_DIR}/duktape/image_data.c
    ${CMAKE_BINARY_DIR}/duktape/keyboard_event.c
    ${CMAKE_BINARY_DIR}/duktape/keyboard_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/location.c
    ${CMAKE_BINARY_DIR}/duktape/media_controller.c
    ${CMAKE_BINARY_DIR}/duktape/media_error.c
    ${CMAKE_BINARY_DIR}/duktape/media_list.c
    ${CMAKE_BINARY_DIR}/duktape/message_channel.c
    ${CMAKE_BINARY_DIR}/duktape/message_event.c
    ${CMAKE_BINARY_DIR}/duktape/message_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/message_port.c
    ${CMAKE_BINARY_DIR}/duktape/mime_type.c
    ${CMAKE_BINARY_DIR}/duktape/mime_type_array.c
    ${CMAKE_BINARY_DIR}/duktape/mouse_event.c
    ${CMAKE_BINARY_DIR}/duktape/mouse_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/mutation_event.c
    ${CMAKE_BINARY_DIR}/duktape/mutation_observer.c
    ${CMAKE_BINARY_DIR}/duktape/mutation_observer_init.c
    ${CMAKE_BINARY_DIR}/duktape/mutation_record.c
    ${CMAKE_BINARY_DIR}/duktape/named_node_map.c
    ${CMAKE_BINARY_DIR}/duktape/navigator.c
    ${CMAKE_BINARY_DIR}/duktape/node.c
    ${CMAKE_BINARY_DIR}/duktape/node_filter.c
    ${CMAKE_BINARY_DIR}/duktape/node_iterator.c
    ${CMAKE_BINARY_DIR}/duktape/node_list.c
    ${CMAKE_BINARY_DIR}/duktape/page_transition_event.c
    ${CMAKE_BINARY_DIR}/duktape/page_transition_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/path2d.c
    ${CMAKE_BINARY_DIR}/duktape/plugin.c
    ${CMAKE_BINARY_DIR}/duktape/plugin_array.c
    ${CMAKE_BINARY_DIR}/duktape/pop_state_event.c
    ${CMAKE_BINARY_DIR}/duktape/pop_state_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/processing_instruction.c
    ${CMAKE_BINARY_DIR}/duktape/pseudo_element.c
    ${CMAKE_BINARY_DIR}/duktape/radio_node_list.c
    ${CMAKE_BINARY_DIR}/duktape/range.c
    ${CMAKE_BINARY_DIR}/duktape/related_event.c
    ${CMAKE_BINARY_DIR}/duktape/related_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/shared_worker.c
    ${CMAKE_BINARY_DIR}/duktape/shared_worker_global_scope.c
    ${CMAKE_BINARY_DIR}/duktape/storage.c
    ${CMAKE_BINARY_DIR}/duktape/storage_event.c
    ${CMAKE_BINARY_DIR}/duktape/storage_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/style_sheet.c
    ${CMAKE_BINARY_DIR}/duktape/style_sheet_list.c
    ${CMAKE_BINARY_DIR}/duktape/svg_element.c
    ${CMAKE_BINARY_DIR}/duktape/text.c
    ${CMAKE_BINARY_DIR}/duktape/text_metrics.c
    ${CMAKE_BINARY_DIR}/duktape/text_track.c
    ${CMAKE_BINARY_DIR}/duktape/text_track_cue.c
    ${CMAKE_BINARY_DIR}/duktape/text_track_cue_list.c
    ${CMAKE_BINARY_DIR}/duktape/text_track_list.c
    ${CMAKE_BINARY_DIR}/duktape/time_ranges.c
    ${CMAKE_BINARY_DIR}/duktape/touch.c
    ${CMAKE_BINARY_DIR}/duktape/track_event.c
    ${CMAKE_BINARY_DIR}/duktape/track_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/tree_walker.c
    ${CMAKE_BINARY_DIR}/duktape/ui_event.c
    ${CMAKE_BINARY_DIR}/duktape/ui_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/url.c
    ${CMAKE_BINARY_DIR}/duktape/url_search_params.c
    ${CMAKE_BINARY_DIR}/duktape/validity_state.c
    ${CMAKE_BINARY_DIR}/duktape/video_track.c
    ${CMAKE_BINARY_DIR}/duktape/video_track_list.c
    ${CMAKE_BINARY_DIR}/duktape/web_socket.c
    ${CMAKE_BINARY_DIR}/duktape/wheel_event.c
    ${CMAKE_BINARY_DIR}/duktape/wheel_event_init.c
    ${CMAKE_BINARY_DIR}/duktape/window.c
    ${CMAKE_BINARY_DIR}/duktape/worker.c
    ${CMAKE_BINARY_DIR}/duktape/worker_global_scope.c
    ${CMAKE_BINARY_DIR}/duktape/worker_location.c
    ${CMAKE_BINARY_DIR}/duktape/worker_navigator.c
    ${CMAKE_BINARY_DIR}/duktape/xml_document.c
    ${CMAKE_BINARY_DIR}/duktape/xml_serializer.c
)
add_custom_command(
    OUTPUT ${CMAKE_BINARY_DIR}/duktape/binding.h ${CMAKE_BINARY_DIR}/duktape/binding.c ${CMAKE_BINARY_DIR}/duktape/private.h ${CMAKE_BINARY_DIR}/duktape/prototype.h ${DUKTAPE_GEN_SOURCES}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/duktape
    COMMAND $<TARGET_FILE:nsgenbind> -I ${CMAKE_SOURCE_DIR}/src/content/handlers/javascript/WebIDL neosurf.bnd ${CMAKE_BINARY_DIR}/duktape
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/src/content/handlers/javascript/duktape
    DEPENDS nsgenbind ${DUKTAPE_BND} ${WEBIDL_SOURCES}
)
add_custom_target(duktape_bindings DEPENDS ${CMAKE_BINARY_DIR}/duktape/binding.h ${CMAKE_BINARY_DIR}/duktape/binding.c ${DUKTAPE_GEN_SOURCES})
