function(libcss_extract_property_names gen_file out_var)
  file(READ ${gen_file} _contents)
  string(REPLACE "\r\n" "\n" _contents "${_contents}")
  string(REPLACE "\r" "\n" _contents "${_contents}")
  string(REPLACE "\n" ";" _lines "${_contents}")
  set(_names)
  foreach(_line ${_lines})
    string(STRIP "${_line}" _line_stripped)
    if(NOT _line_stripped STREQUAL "" AND NOT _line_stripped MATCHES "^#")
      string(REGEX MATCH "^([^:]+)" _name "${_line_stripped}")
      list(APPEND _names "${CMAKE_MATCH_1}")
    endif()
  endforeach()
  set(${out_var} "${_names}" PARENT_SCOPE)
endfunction()
