#!/usr/bin/env python3
"""CMake configure-time helpers for libcss.

Reads properties.toml and provides subcommands used by CMakeLists.txt
at configure time via execute_process().

Usage:
    cmake_helpers.py check-toml
    cmake_helpers.py property-names <properties.toml>
    cmake_helpers.py cascade-split <properties.toml>
"""
import sys

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore[no-redef]


def _load_toml(path):
    """Load and return TOML data from the given file path."""
    with open(path, 'rb') as f:
        return tomllib.load(f)


def cmd_check_toml():
    """Verify that Python can parse TOML files.

    Prints 'ok' on success.  The TOML import at module level already did
    the real check — if we got this far, it works.
    """
    print('ok')


def cmd_property_names(toml_path):
    """Extract property names for gen_parser output targets.

    Prints a semicolon-separated list of property names that gen_parser
    will generate autogenerated_*.c files for:
      - Regular properties with a 'parse' field (not manual/shorthand)
      - Generic (WRAP) entries from [generic.*]

    Output is consumed by CMake's foreach() via string(REPLACE).
    """
    data = _load_toml(toml_path)

    names = []

    # Regular properties with parse specs
    for name, props in sorted(data.items()):
        if not isinstance(props, dict):
            continue
        if not props.get('parse'):
            continue
        if props.get('manual') or props.get('shorthand'):
            continue
        names.append(name)

    # Generic (WRAP) entries: [generic.*] → autogenerated_*.c
    generics = data.get('generic', {})
    if isinstance(generics, dict):
        names.extend(sorted(generics.keys()))

    print(';'.join(names))


def cmd_cascade_split(toml_path):
    """Split CSS_PROP_ properties into generated vs manual cascade sources.

    Output format (consumed by CMake string(REGEX MATCH)):
        GENERATED:name1;name2;...
        MANUAL:name1;name2;...
    Or on error:
        ERROR:name1;name2;...
    """
    data = _load_toml(toml_path)

    generated = []
    manual = []
    errors = []

    for name, props in data.items():
        if not isinstance(props, dict):
            continue
        if not props.get('enum', '').startswith('CSS_PROP_'):
            continue
        cascade = props.get('cascade')
        if cascade is None:
            errors.append(name)
            continue
        if cascade == 'none':
            continue
        elif cascade == 'manual':
            manual.append(name)
        else:
            generated.append(name)

    if errors:
        print('ERROR:' + ';'.join(errors))
    else:
        print('GENERATED:' + ';'.join(sorted(generated)))
        print('MANUAL:' + ';'.join(sorted(manual)))


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <command> [args...]", file=sys.stderr)
        print("Commands: check-toml, property-names, cascade-split", file=sys.stderr)
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == 'check-toml':
        cmd_check_toml()
    elif cmd == 'property-names':
        if len(sys.argv) < 3:
            print("Usage: property-names <properties.toml>", file=sys.stderr)
            sys.exit(1)
        cmd_property_names(sys.argv[2])
    elif cmd == 'cascade-split':
        if len(sys.argv) < 3:
            print("Usage: cascade-split <properties.toml>", file=sys.stderr)
            sys.exit(1)
        cmd_cascade_split(sys.argv[2])
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        print("Commands: check-toml, property-names, cascade-split", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
